{"name": "Авторизация в приложении пройдет неуспешно, если обязательное поле password не передано", "status": "failed", "statusDetails": {"message": "AssertionError: assert (504 == 400)\n +  where 504 = <Response [504]>.status_code", "trace": "self = <tests_api.TestLoginCourier object at 0x000001FC3C007190>, courier = ['dllbeuxbyv', 'pxjvcgfhso', 'pgahkkegmi']\n\n    @allure.title('Авторизация в приложении пройдет неуспешно, если обязательное поле password не передано')\n    def test_login_couriers_required_field_password_not_sending(self, courier):\n        # создаем курьера\n        data = courier\n        login = data[0]\n    \n        # логинимся под созданным курьером без пароля\n        endpoint_login_courier = '/api/v1/courier/login'\n        data_login = {\n            \"login\": login\n        }\n        response = requests.post(f'{url}{endpoint_login_courier}', data=data_login)\n>       assert response.status_code == 400 and response.text == '{\"message\":  \"Недостаточно данных для входа\"}'\nE       assert (504 == 400)\nE        +  where 504 = <Response [504]>.status_code\n\ntests\\tests_api.py:197: AssertionError"}, "start": 1698773356420, "stop": 1698773417472, "uuid": "fa069dca-9056-40e5-a3ac-2b6153c86707", "historyId": "18c01afc009a270b7786b353c03b0a96", "testCaseId": "18c01afc009a270b7786b353c03b0a96", "fullName": "tests.tests_api.TestLoginCourier#test_login_couriers_required_field_password_not_sending", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_api"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-QT86LB7"}, {"name": "thread", "value": "5048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_api"}]}